//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.SmartSuitcase.Controls
{


    public partial class ucSmartSuitcasePage
    {

        /// <summary>
        /// ucHero control.
        /// </summary>
        protected global::System.Web.UI.UserControl ucHero;

        /// <summary>
        /// ucServices control.
        /// </summary>
        protected global::System.Web.UI.UserControl ucServices;

        /// <summary>
        /// ucAccess control.
        /// </summary>
        protected global::System.Web.UI.UserControl ucAccess;

        /// <summary>
        /// ucFaq control.
        /// </summary>
        protected global::System.Web.UI.UserControl ucFaq;

        /// <summary>
        /// ucSupport control.
        /// </summary>
        protected global::System.Web.UI.UserControl ucSupport;
    }
}
