//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.SmartSuitcase.Controls
{


    public partial class ucSmartSuitcaseFaq
    {

        /// <summary>
        /// secFaq control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl secFaq;

        /// <summary>
        /// phHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phHeading;

        /// <summary>
        /// ltSectionTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltSectionTitle;

        /// <summary>
        /// rptFaq control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFaq;
    }
}
