using System;
using System.Collections.Generic;
using System.Globalization;
using Microsoft.SharePoint;

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.About
{
    /// <summary>
    /// Idempotent provisioner for the OrgStructureUnits list. Creates the list and
    /// its fields if missing, grants anonymous read, and seeds the 84 default units
    /// ONLY when the list is first created (never re-seeds an existing list).
    /// Field provisioning is C# only — no PowerShell.
    /// </summary>
    public static class OrgStructureProvisioner
    {
        public const string ListName = "OrgStructureUnits";

        // Internal field names
        public const string F_Order = "OrgOrder";
        public const string F_Selector = "OrgSelector";
        public const string F_TitleEn = "TitleEn";
        public const string F_Desc = "OrgDesc";
        public const string F_DescEn = "OrgDescEn";
        public const string F_Badge = "OrgBadge";
        public const string F_BadgeEn = "OrgBadgeEn";
        public const string F_Meta = "OrgMeta";
        public const string F_MetaEn = "OrgMetaEn";
        public const string F_Icon = "OrgIcon";
        public const string F_Theme = "OrgTheme";
        public const string F_TextColor = "OrgTextColor";
        public const string F_LinkUrl = "OrgLinkUrl";
        public const string F_Active = "OrgActive";

        /// <summary>
        /// Ensures the list on a specific web (by server-relative URL, e.g. /ar/AboutUniversity/),
        /// under elevated privileges so a content editor without "Manage Lists" can still trigger
        /// first-time provisioning. Call from OnInit for AUTHENTICATED users only.
        /// </summary>
        public static void EnsureListAt(Guid siteId, string webServerRelativeUrl)
        {
            try
            {
                string url = OrgStructureRepository.Normalize(webServerRelativeUrl, "/");
                SPSecurity.RunWithElevatedPrivileges(delegate
                {
                    using (var site = new SPSite(siteId))
                    using (var web = site.OpenWeb(url))
                    {
                        if (web != null && web.Exists) EnsureList(web);
                    }
                });
            }
            catch (Exception ex)
            {
                Publics.WriteToLog(GetUrl(), "OrgStructureProvisioner.EnsureListAt", ex.Message);
            }
        }

        /// <summary>
        /// Ensures the list exists with all fields and (on first creation) seed data.
        /// Call from OnInit for AUTHENTICATED users only.
        /// </summary>
        public static SPList EnsureList(SPWeb web)
        {
            if (web == null) return null;

            SPList list = web.Lists.TryGetList(ListName);
            bool created = false;

            bool allowUnsafe = web.AllowUnsafeUpdates;
            try
            {
                web.AllowUnsafeUpdates = true;

                if (list == null)
                {
                    Guid id = web.Lists.Add(ListName, "PNU organizational structure units", SPListTemplateType.GenericList);
                    list = web.Lists[id];
                    created = true;
                }

                EnsureField(list, F_Order, SPFieldType.Number, "Order");
                EnsureField(list, F_Selector, SPFieldType.Note, "Selector");
                EnsureField(list, F_TitleEn, SPFieldType.Text, "Title (EN)");
                EnsureField(list, F_Desc, SPFieldType.Note, "Description (AR)");
                EnsureField(list, F_DescEn, SPFieldType.Note, "Description (EN)");
                EnsureField(list, F_Badge, SPFieldType.Text, "Badge (AR)");
                EnsureField(list, F_BadgeEn, SPFieldType.Text, "Badge (EN)");
                EnsureField(list, F_Meta, SPFieldType.Text, "Meta (AR)");
                EnsureField(list, F_MetaEn, SPFieldType.Text, "Meta (EN)");
                EnsureField(list, F_Icon, SPFieldType.Text, "Icon");
                EnsureField(list, F_Theme, SPFieldType.Text, "Theme");
                EnsureField(list, F_TextColor, SPFieldType.Text, "Text Color");
                // Link stored as plain text Note (URLs can exceed 255 chars / avoid Hyperlink field limits).
                EnsureField(list, F_LinkUrl, SPFieldType.Note, "Link URL");
                EnsureField(list, F_Active, SPFieldType.Boolean, "Active");

                list.Update();

                if (created)
                {
                    Seed(list);
                }

                GrantAnonymousRead(web, list);
            }
            catch (Exception ex)
            {
                Publics.WriteToLog(GetUrl(), "OrgStructureProvisioner.EnsureList", ex.Message);
            }
            finally
            {
                web.AllowUnsafeUpdates = allowUnsafe;
            }

            return list;
        }

        private static void EnsureField(SPList list, string internalName, SPFieldType type, string displayName)
        {
            if (list.Fields.ContainsField(internalName)) return;

            string created = list.Fields.Add(internalName, type, false);
            SPField fld = list.Fields.GetFieldByInternalName(created);

            if (type == SPFieldType.Note)
            {
                SPFieldMultiLineText note = fld as SPFieldMultiLineText;
                if (note != null)
                {
                    note.RichText = false;   // Plain text mode
                    note.Update();
                }
            }

            if (!string.IsNullOrEmpty(displayName) && fld.Title != displayName)
            {
                fld.Title = displayName;
                fld.Update();
            }
        }

        private static void GrantAnonymousRead(SPWeb web, SPList list)
        {
            try
            {
                if (list == null) return;
                list.BreakRoleInheritance(true, false);
                list.AnonymousPermMask64 = SPBasePermissions.ViewListItems | SPBasePermissions.ViewVersions | SPBasePermissions.Open;
                list.Update();
            }
            catch (Exception ex)
            {
                Publics.WriteToLog(GetUrl(), "OrgStructureProvisioner.GrantAnonymousRead", ex.Message);
            }
        }

        private static void Seed(SPList list)
        {
            foreach (OrgStructureUnit u in DefaultUnits())
            {
                SPListItem item = list.AddItem();
                item["Title"] = u.Title;
                item[F_TitleEn] = u.TitleEn;
                item[F_Order] = u.Order;
                item[F_Selector] = u.Selector;
                item[F_Desc] = u.Description;
                item[F_DescEn] = u.DescriptionEn;
                item[F_Badge] = u.Badge;
                item[F_BadgeEn] = u.BadgeEn;
                item[F_Meta] = u.Meta;
                item[F_MetaEn] = u.MetaEn;
                item[F_Icon] = u.Icon;
                item[F_Theme] = u.Theme;
                item[F_TextColor] = u.TextColor;
                item[F_LinkUrl] = u.LinkUrl;
                item[F_Active] = u.Active;
                item.Update();
            }
        }

        private static string GetUrl()
        {
            try
            {
                return System.Web.HttpContext.Current != null
                    ? System.Web.HttpContext.Current.Request.Url.ToString()
                    : string.Empty;
            }
            catch { return string.Empty; }
        }

        /// <summary>The 84 default PNU organizational units (Arabic seed content).</summary>
        public static List<OrgStructureUnit> DefaultUnits()
        {
            return new List<OrgStructureUnit>
            {
            new OrgStructureUnit { Order = 10, Selector = "rect[x=\"482.5\"][y=\"79.5\"][width=\"280\"][height=\"56\"]", Title = "مجلس الجامعة", TitleEn = "University Council", Description = "مجلس الجامعة — جهة إشرافية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "University Council — Supervisory body within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة إشرافية", BadgeEn = "Supervisory body", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary)", LinkUrl = "pnu-university-council.aspx", Active = true },
            new OrgStructureUnit { Order = 20, Selector = "rect[x=\"255.5\"][y=\"141.5\"][width=\"135\"][height=\"52\"]", Title = "المجالس الاستشارية", TitleEn = "Advisory Councils", Description = "المجالس الاستشارية — جهة إشرافية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Advisory Councils — Supervisory body within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة إشرافية", BadgeEn = "Supervisory body", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 30, Selector = "rect[x=\"482.5\"][y=\"165.5\"][width=\"280\"][height=\"56\"]", Title = "رئيسة الجامعة", TitleEn = "University President", Description = "رئيسة الجامعة — قيادة تنفيذية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "University President — Executive leadership within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "قيادة تنفيذية", BadgeEn = "Executive leadership", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "sa", TextColor = "var(--dga-primary-25)", LinkUrl = "university-president-message.aspx", Active = true },
            new OrgStructureUnit { Order = 40, Selector = "rect[x=\"852.5\"][y=\"172.5\"][width=\"135\"][height=\"52\"]", Title = "أمانة مجلس الجامعة", TitleEn = "University Council Secretariat", Description = "أمانة مجلس الجامعة — دعم إداري ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "University Council Secretariat — Administrative support within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "دعم إداري", BadgeEn = "Administrative support", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "pnu-university-council.aspx", Active = true },
            new OrgStructureUnit { Order = 50, Selector = "rect[x=\"255.5\"][y=\"203.5\"][width=\"135\"][height=\"52\"]", Title = "مجالس التوجهات الاستراتيجية", TitleEn = "Strategic Directions Councils", Description = "مجالس التوجهات الاستراتيجية — جهة إشرافية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Strategic Directions Councils — Supervisory body within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة إشرافية", BadgeEn = "Supervisory body", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 60, Selector = "rect[x=\"632.5\"][y=\"234.5\"][width=\"135\"][height=\"40\"]", Title = "مكتب رئيسة الجامعة", TitleEn = "Office of the University President", Description = "مكتب رئيسة الجامعة — قيادة تنفيذية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Office of the University President — Executive leadership within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "قيادة تنفيذية", BadgeEn = "Executive leadership", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "university-president-message.aspx", Active = true },
            new OrgStructureUnit { Order = 70, Selector = "rect[x=\"477.5\"][y=\"234.5\"][width=\"135\"][height=\"40\"]", Title = "مكتب رعاية المستفيدين", TitleEn = "Beneficiary Care Office", Description = "مكتب رعاية المستفيدين — مكتب ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Beneficiary Care Office — Office within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مكتب", BadgeEn = "Office", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-calendar-03", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 80, Selector = "rect[x=\"1073.5\"][y=\"493.5\"][width=\"163\"][height=\"80\"]", Title = "وكالة الجامعة", TitleEn = "University Vice-Presidency", Description = "وكالة الجامعة — وكالة رئيسية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "University Vice-Presidency — Main vice-presidency within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وكالة رئيسية", BadgeEn = "Main vice-presidency", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "sa", TextColor = "var(--dga-primary-25)", LinkUrl = "agency-details.aspx", Active = true },
            new OrgStructureUnit { Order = 90, Selector = "rect[x=\"864.5\"][y=\"493.5\"][width=\"163\"][height=\"80\"]", Title = "وكالة الجامعة للشؤون الأكاديمية", TitleEn = "Vice-Presidency for Academic Affairs", Description = "وكالة الجامعة للشؤون الأكاديمية — وكالة رئيسية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Vice-Presidency for Academic Affairs — Main vice-presidency within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وكالة رئيسية", BadgeEn = "Main vice-presidency", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "sa", TextColor = "var(--dga-primary-25)", LinkUrl = "agency-details.aspx", Active = true },
            new OrgStructureUnit { Order = 100, Selector = "rect[x=\"216.5\"][y=\"493.5\"][width=\"163\"][height=\"80\"]", Title = "وكالة الجامعة للدراسات العليا والبحث العلمي", TitleEn = "Vice-Presidency for Graduate Studies and Scientific Research", Description = "وكالة الجامعة للدراسات العليا والبحث العلمي — وكالة رئيسية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Vice-Presidency for Graduate Studies and Scientific Research — Main vice-presidency within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وكالة رئيسية", BadgeEn = "Main vice-presidency", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "sa", TextColor = "var(--dga-primary-25)", LinkUrl = "agency-details.aspx", Active = true },
            new OrgStructureUnit { Order = 110, Selector = "rect[x=\"1.5\"][y=\"493.5\"][width=\"163\"][height=\"80\"]", Title = "وكالة الجامعة للأصول والاستثمار", TitleEn = "Vice-Presidency for Assets and Investment", Description = "وكالة الجامعة للأصول والاستثمار — وكالة رئيسية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Vice-Presidency for Assets and Investment — Main vice-presidency within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وكالة رئيسية", BadgeEn = "Main vice-presidency", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-hierarchy", Theme = "sa", TextColor = "var(--dga-primary-25)", LinkUrl = "agency-details.aspx", Active = true },
            new OrgStructureUnit { Order = 120, Selector = "rect[x=\"1073.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الميزانية", TitleEn = "Budget Department", Description = "إدارة الميزانية — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Budget Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 130, Selector = "rect[x=\"864.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "عمادة القبول والتسجيل", TitleEn = "Deanship of Admission and Registration", Description = "عمادة القبول والتسجيل — عمادة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Deanship of Admission and Registration — Deanship within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "عمادة", BadgeEn = "Deanship", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "deanship-details.aspx", Active = true },
            new OrgStructureUnit { Order = 140, Selector = "rect[x=\"655.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "مركز سارة السديري لدراسات المرأة", TitleEn = "Sarah Al-Sudairi Center for Women's Studies", Description = "مركز سارة السديري لدراسات المرأة — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Sarah Al-Sudairi Center for Women's Studies — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 150, Selector = "rect[x=\"426.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للشؤون الصحية", TitleEn = "General Department of Health Affairs", Description = "الإدارة العامة للشؤون الصحية — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Health Affairs — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 160, Selector = "rect[x=\"216.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "عمادة الدراسات العليا", TitleEn = "Deanship of Graduate Studies", Description = "عمادة الدراسات العليا — عمادة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Deanship of Graduate Studies — Deanship within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "عمادة", BadgeEn = "Deanship", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "deanship-details.aspx", Active = true },
            new OrgStructureUnit { Order = 170, Selector = "rect[x=\"1.5\"][y=\"589.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للمنشآت والتشغيل", TitleEn = "General Department of Facilities and Operations", Description = "الإدارة العامة للمنشآت والتشغيل — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Facilities and Operations — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 180, Selector = "rect[x=\"1073.5\"][y=\"653.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة المالية", TitleEn = "Finance Department", Description = "الإدارة المالية — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Finance Department — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 190, Selector = "rect[x=\"864.5\"][y=\"653.5\"][width=\"163\"][height=\"52\"]", Title = "عمادة التطوير والجودة", TitleEn = "Deanship of Development and Quality", Description = "عمادة التطوير والجودة — عمادة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Deanship of Development and Quality — Deanship within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "عمادة", BadgeEn = "Deanship", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "deanship-details.aspx", Active = true },
            new OrgStructureUnit { Order = 200, Selector = "rect[x=\"655.5\"][y=\"653.5\"][width=\"163\"][height=\"52\"]", Title = "المرصد الوطني للمرأة", TitleEn = "National Observatory for Women", Description = "المرصد الوطني للمرأة — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "National Observatory for Women — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 210, Selector = "rect[x=\"426.5\"][y=\"653.5\"][width=\"135\"][height=\"52\"]", Title = "مستشفى الملك عبدالله بن عبدالعزيز الجامعي", TitleEn = "King Abdullah bin Abdulaziz University Hospital", Description = "مستشفى الملك عبدالله بن عبدالعزيز الجامعي — مستشفى جامعي ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "King Abdullah bin Abdulaziz University Hospital — University hospital within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مستشفى جامعي", BadgeEn = "University hospital", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 220, Selector = "rect[x=\"216.5\"][y=\"653.5\"][width=\"163\"][height=\"52\"]", Title = "عمادة البحث العلمي والمكتبات", TitleEn = "Deanship of Scientific Research and Libraries", Description = "عمادة البحث العلمي والمكتبات — عمادة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Deanship of Scientific Research and Libraries — Deanship within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "عمادة", BadgeEn = "Deanship", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "deanship-details.aspx", Active = true },
            new OrgStructureUnit { Order = 230, Selector = "rect[x=\"1.5\"][y=\"653.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للاستثمار", TitleEn = "General Department of Investment", Description = "الإدارة العامة للاستثمار — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Investment — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 240, Selector = "rect[x=\"1073.5\"][y=\"717.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة المشتريات والمناقصات", TitleEn = "Procurement and Tenders Department", Description = "إدارة المشتريات والمناقصات — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Procurement and Tenders Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 250, Selector = "rect[x=\"864.5\"][y=\"717.5\"][width=\"163\"][height=\"52\"]", Title = "عمادة شؤون الطالبات", TitleEn = "Deanship of Student Affairs", Description = "عمادة شؤون الطالبات — عمادة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Deanship of Student Affairs — Deanship within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "عمادة", BadgeEn = "Deanship", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "deanship-details.aspx", Active = true },
            new OrgStructureUnit { Order = 260, Selector = "rect[x=\"655.5\"][y=\"717.5\"][width=\"163\"][height=\"52\"]", Title = "مركز أبحاث السلامة السلوكية والنفسية", TitleEn = "Behavioral and Psychological Safety Research Center", Description = "مركز أبحاث السلامة السلوكية والنفسية — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Behavioral and Psychological Safety Research Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 270, Selector = "rect[x=\"426.5\"][y=\"717.5\"][width=\"135\"][height=\"52\"]", Title = "مركز المهارات والمحاكاة الطبي", TitleEn = "Medical Skills and Simulation Center", Description = "مركز المهارات والمحاكاة الطبي — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Medical Skills and Simulation Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 280, Selector = "rect[x=\"216.5\"][y=\"717.5\"][width=\"163\"][height=\"52\"]", Title = "المجلس العلمي", TitleEn = "Scientific Council", Description = "المجلس العلمي — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Scientific Council — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "primary", TextColor = "var(--dga-primary)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 290, Selector = "rect[x=\"1.5\"][y=\"717.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الإيرادات البديلة", TitleEn = "Alternative Revenues Department", Description = "إدارة الإيرادات البديلة — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Alternative Revenues Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 300, Selector = "rect[x=\"1073.5\"][y=\"781.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة المستودعات", TitleEn = "Warehouses Department", Description = "إدارة المستودعات — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Warehouses Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 310, Selector = "rect[x=\"864.5\"][y=\"781.5\"][width=\"163\"][height=\"52\"]", Title = "مركز الدعم الطلابي والمهني", TitleEn = "Student and Career Support Center", Description = "مركز الدعم الطلابي والمهني — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Student and Career Support Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 320, Selector = "rect[x=\"655.5\"][y=\"781.5\"][width=\"163\"][height=\"52\"]", Title = "معهد التنمية والخدمات الاستشارية", TitleEn = "Institute of Development and Consulting Services", Description = "معهد التنمية والخدمات الاستشارية — معهد ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Institute of Development and Consulting Services — Institute within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "معهد", BadgeEn = "Institute", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-globe", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 330, Selector = "rect[x=\"426.5\"][y=\"781.5\"][width=\"135\"][height=\"52\"]", Title = "مركز أبحاث العلوم الطبيعية والصحية", TitleEn = "Natural and Health Sciences Research Center", Description = "مركز أبحاث العلوم الطبيعية والصحية — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Natural and Health Sciences Research Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 340, Selector = "rect[x=\"216.5\"][y=\"781.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة كراسي البحث", TitleEn = "Research Chairs Department", Description = "إدارة كراسي البحث — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Research Chairs Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 350, Selector = "rect[x=\"1.5\"][y=\"781.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الأصول", TitleEn = "Assets Department", Description = "إدارة الأصول — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Assets Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 360, Selector = "rect[x=\"1073.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "مركز الوثائق والمحفوظات", TitleEn = "Documents and Archives Center", Description = "مركز الوثائق والمحفوظات — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Documents and Archives Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 370, Selector = "rect[x=\"864.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة التعلم الإلكتروني", TitleEn = "E-Learning Department", Description = "إدارة التعلم الإلكتروني — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "E-Learning Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 380, Selector = "rect[x=\"655.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الأوقاف", TitleEn = "Endowments Department", Description = "إدارة الأوقاف — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Endowments Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 390, Selector = "rect[x=\"426.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للحوكمة والمخاطر والالتزام", TitleEn = "General Department of Governance, Risk and Compliance", Description = "الإدارة العامة للحوكمة والمخاطر والالتزام — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Governance, Risk and Compliance — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 400, Selector = "rect[x=\"216.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "مركز الأبحاث العلمية", TitleEn = "Scientific Research Center", Description = "مركز الأبحاث العلمية — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Scientific Research Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 410, Selector = "rect[x=\"1.5\"][y=\"845.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة السلامة والمخاطر", TitleEn = "Safety and Risk Department", Description = "إدارة السلامة والمخاطر — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Safety and Risk Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 420, Selector = "rect[x=\"1073.5\"][y=\"909.5\"][width=\"163\"][height=\"52\"]", Title = "الاتصالات الإدارية المركزية", TitleEn = "Central Administrative Communications", Description = "الاتصالات الإدارية المركزية — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Central Administrative Communications — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 430, Selector = "rect[x=\"864.5\"][y=\"909.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة البرامج الأكاديمية", TitleEn = "Academic Programs Department", Description = "إدارة البرامج الأكاديمية — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Academic Programs Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 440, Selector = "rect[x=\"655.5\"][y=\"909.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الإعلام والتأثير المعرفي", TitleEn = "Media and Knowledge Impact Department", Description = "إدارة الإعلام والتأثير المعرفي — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Media and Knowledge Impact Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 450, Selector = "rect[x=\"426.5\"][y=\"909.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للموارد البشرية", TitleEn = "General Department of Human Resources", Description = "الإدارة العامة للموارد البشرية — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Human Resources — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 460, Selector = "rect[x=\"216.5\"][y=\"909.5\"][width=\"163\"][height=\"52\"]", Title = "مركز الابتكار وريادة الأعمال", TitleEn = "Innovation and Entrepreneurship Center", Description = "مركز الابتكار وريادة الأعمال — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Innovation and Entrepreneurship Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 470, Selector = "rect[x=\"1073.5\"][y=\"973.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الحركة والنقل", TitleEn = "Movement and Transportation Department", Description = "إدارة الحركة والنقل — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Movement and Transportation Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 480, Selector = "rect[x=\"864.5\"][y=\"973.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة برنامج السنة التأسيسية للكليات الصحية", TitleEn = "Health Colleges Foundation Year Program Department", Description = "إدارة برنامج السنة التأسيسية للكليات الصحية — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Health Colleges Foundation Year Program Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 490, Selector = "rect[x=\"655.5\"][y=\"973.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة القانونية", TitleEn = "Legal Department", Description = "الإدارة القانونية — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Legal Department — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 500, Selector = "rect[x=\"426.5\"][y=\"973.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للتحول الرقمي", TitleEn = "General Department of Digital Transformation", Description = "الإدارة العامة للتحول الرقمي — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Digital Transformation — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 510, Selector = "rect[x=\"216.5\"][y=\"973.5\"][width=\"163\"][height=\"52\"]", Title = "مركز الأبحاث الإنسانية", TitleEn = "Humanities Research Center", Description = "مركز الأبحاث الإنسانية — مركز ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Humanities Research Center — Center within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مركز", BadgeEn = "Center", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 520, Selector = "rect[x=\"1073.5\"][y=\"1037.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للأمن", TitleEn = "General Department of Security", Description = "الإدارة العامة للأمن — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Security — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 530, Selector = "rect[x=\"864.5\"][y=\"1037.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة مقررات المتطلبات العامة", TitleEn = "General Requirements Courses Department", Description = "إدارة مقررات المتطلبات العامة — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Requirements Courses Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 540, Selector = "rect[x=\"655.5\"][y=\"1037.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة مراقبة المخزون", TitleEn = "Inventory Control Department", Description = "إدارة مراقبة المخزون — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Inventory Control Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 550, Selector = "rect[x=\"426.5\"][y=\"1037.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للمراجعة الداخلية", TitleEn = "General Department of Internal Audit", Description = "الإدارة العامة للمراجعة الداخلية — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Internal Audit — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 560, Selector = "rect[x=\"216.5\"][y=\"1037.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الابتعاث والتدريب والإشراف المشترك", TitleEn = "Scholarships, Training and Joint Supervision Department", Description = "إدارة الابتعاث والتدريب والإشراف المشترك — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Scholarships, Training and Joint Supervision Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 570, Selector = "rect[x=\"864.5\"][y=\"1101.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة التبادل الطلابي", TitleEn = "Student Exchange Department", Description = "إدارة التبادل الطلابي — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Student Exchange Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 580, Selector = "rect[x=\"655.5\"][y=\"1101.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الأمن السيبراني", TitleEn = "Cybersecurity Department", Description = "إدارة الأمن السيبراني — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Cybersecurity Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 590, Selector = "rect[x=\"426.5\"][y=\"1101.5\"][width=\"163\"][height=\"52\"]", Title = "الإدارة العامة للاتصال المؤسسي", TitleEn = "General Department of Corporate Communication", Description = "الإدارة العامة للاتصال المؤسسي — إدارة عامة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "General Department of Corporate Communication — General department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة عامة", BadgeEn = "General department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 600, Selector = "rect[x=\"216.5\"][y=\"1101.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة المؤتمرات والندوات", TitleEn = "Conferences and Seminars Department", Description = "إدارة المؤتمرات والندوات — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Conferences and Seminars Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 610, Selector = "rect[x=\"864.5\"][y=\"1165.5\"][width=\"163\"][height=\"52\"]", Title = "الكليات والمعاهد", TitleEn = "Colleges and Institutes", Description = "الكليات والمعاهد — جهة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Colleges and Institutes — Organizational entity within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "جهة تنظيمية", BadgeEn = "Organizational entity", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 620, Selector = "rect[x=\"655.5\"][y=\"1165.5\"][width=\"163\"][height=\"52\"]", Title = "وحدة التوعية الفكرية", TitleEn = "Intellectual Awareness Unit", Description = "وحدة التوعية الفكرية — وحدة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Intellectual Awareness Unit — Organizational unit within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وحدة تنظيمية", BadgeEn = "Organizational unit", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 630, Selector = "rect[x=\"426.5\"][y=\"1165.5\"][width=\"163\"][height=\"52\"]", Title = "بوابة نورة للتحول", TitleEn = "Noura Transformation Portal", Description = "بوابة نورة للتحول — منصة رقمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Noura Transformation Portal — Digital platform within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "منصة رقمية", BadgeEn = "Digital platform", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-globe", Theme = "saMuted", TextColor = "var(--dga-primary-25)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 640, Selector = "rect[x=\"216.5\"][y=\"1165.5\"][width=\"163\"][height=\"52\"]", Title = "إدارة الجمعيات والمجلات العلمية", TitleEn = "Scientific Societies and Journals Department", Description = "إدارة الجمعيات والمجلات العلمية — إدارة ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Scientific Societies and Journals Department — Department within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "إدارة", BadgeEn = "Department", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-chart", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 650, Selector = "rect[x=\"655.5\"][y=\"1229.5\"][width=\"163\"][height=\"52\"]", Title = "مكتب إدارة البيانات", TitleEn = "Data Management Office", Description = "مكتب إدارة البيانات — مكتب ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Data Management Office — Office within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "مكتب", BadgeEn = "Office", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-calendar-03", Theme = "saMuted", TextColor = "var(--dga-primary-950)", LinkUrl = "all-departments.aspx", Active = true },
            new OrgStructureUnit { Order = 660, Selector = "rect[x=\"216.5\"][y=\"1229.5\"][width=\"163\"][height=\"52\"]", Title = "وحدة البحث والتطوير والابتكار", TitleEn = "Research, Development and Innovation Unit", Description = "وحدة البحث والتطوير والابتكار — وحدة تنظيمية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Research, Development and Innovation Unit — Organizational unit within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "وحدة تنظيمية", BadgeEn = "Organizational unit", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-target-01", Theme = "saSoft", TextColor = "var(--dga-primary-950)", LinkUrl = "", Active = true },
            new OrgStructureUnit { Order = 670, Selector = "rect[x=\"949.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية الطب البشري", TitleEn = "College of Medicine", Description = "كلية الطب البشري — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Medicine — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 680, Selector = "rect[x=\"789.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية طب الأسنان", TitleEn = "College of Dentistry", Description = "كلية طب الأسنان — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Dentistry — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 690, Selector = "rect[x=\"629.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية الصيدلية", TitleEn = "College of Pharmacy", Description = "كلية الصيدلية — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Pharmacy — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 700, Selector = "rect[x=\"469.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية الصحة وعلم التأهيل", TitleEn = "College of Health and Rehabilitation Sciences", Description = "كلية الصحة وعلم التأهيل — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Health and Rehabilitation Sciences — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 710, Selector = "rect[x=\"309.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية التمريض", TitleEn = "College of Nursing", Description = "كلية التمريض — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Nursing — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 720, Selector = "rect[x=\"149.5\"][y=\"1415.5\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية العلوم", TitleEn = "College of Sciences", Description = "كلية العلوم — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Sciences — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 730, Selector = "rect[x=\"949.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية علوم الرياضة والنشاط البدني", TitleEn = "College of Sports Science and Physical Activity", Description = "كلية علوم الرياضة والنشاط البدني — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Sports Science and Physical Activity — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 740, Selector = "rect[x=\"789.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية العلوم الأنسانية والإجتماعية", TitleEn = "College of Humanities and Social Sciences", Description = "كلية العلوم الأنسانية والإجتماعية — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Humanities and Social Sciences — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 750, Selector = "rect[x=\"629.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية التربية والتنمية البشرية", TitleEn = "College of Education and Human Development", Description = "كلية التربية والتنمية البشرية — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Education and Human Development — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 760, Selector = "rect[x=\"469.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية اللغات", TitleEn = "College of Languages", Description = "كلية اللغات — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Languages — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 770, Selector = "rect[x=\"309.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية التصاميم والفنون", TitleEn = "College of Designs and Arts", Description = "كلية التصاميم والفنون — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Designs and Arts — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 780, Selector = "rect[x=\"149.5\"][y=\"1493.62\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية القانون", TitleEn = "College of Law", Description = "كلية القانون — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Law — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 790, Selector = "rect[x=\"949.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية علوم الحاسب والمعلومات", TitleEn = "College of Computer and Information Sciences", Description = "كلية علوم الحاسب والمعلومات — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Computer and Information Sciences — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 800, Selector = "rect[x=\"789.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية إدارة الأعمال", TitleEn = "College of Business Administration", Description = "كلية إدارة الأعمال — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Business Administration — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 810, Selector = "rect[x=\"629.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "كلية الهندسة", TitleEn = "College of Engineering", Description = "كلية الهندسة — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "College of Engineering — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 820, Selector = "rect[x=\"469.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "الكلية التطبيقية", TitleEn = "Applied College", Description = "الكلية التطبيقية — كلية ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Applied College — College within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "كلية", BadgeEn = "College", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-user-group", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 830, Selector = "rect[x=\"309.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "معهد تعلم اللغة العربية للناطقات بغيرها", TitleEn = "Institute of Teaching Arabic to Non-Native Speakers", Description = "معهد تعلم اللغة العربية للناطقات بغيرها — معهد ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "Institute of Teaching Arabic to Non-Native Speakers — Institute within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "معهد", BadgeEn = "Institute", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-globe", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            new OrgStructureUnit { Order = 840, Selector = "rect[x=\"149.5\"][y=\"1571.74\"][width=\"135\"][height=\"52.7573\"]", Title = "معهد اللغة الإنجليزية", TitleEn = "English Language Institute", Description = "معهد اللغة الإنجليزية — معهد ضمن الهيكل التنظيمي لجامعة الأميرة نورة بنت عبدالرحمن.", DescriptionEn = "English Language Institute — Institute within the organizational structure of Princess Nourah bint Abdulrahman University.", Badge = "معهد", BadgeEn = "Institute", Meta = "الهيكل التنظيمي", MetaEn = "Organizational structure", Icon = "hgi-globe", Theme = "primary", TextColor = "var(--dga-primary-900)", LinkUrl = "faculty-details.aspx", Active = true },
            };
        }
    }
}
