//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.About.OrgStructure
{
    public partial class ucOrgStructureAdmin
    {
        protected global::System.Web.UI.WebControls.Panel pnlDenied;
        protected global::System.Web.UI.WebControls.Literal litDenied;

        protected global::System.Web.UI.WebControls.Panel pnlAdmin;
        protected global::System.Web.UI.WebControls.Literal litHeader;
        protected global::System.Web.UI.WebControls.LinkButton btnNew;
        protected global::System.Web.UI.WebControls.Literal litNew;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;

        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.HiddenField hidId;

        protected global::System.Web.UI.WebControls.TextBox txtOrder;
        protected global::System.Web.UI.WebControls.Literal litLblOrder;
        protected global::System.Web.UI.WebControls.DropDownList ddlTheme;
        protected global::System.Web.UI.WebControls.Literal litLblTheme;
        protected global::System.Web.UI.WebControls.TextBox txtIcon;
        protected global::System.Web.UI.WebControls.Literal litLblIcon;
        protected global::System.Web.UI.WebControls.TextBox txtSelector;
        protected global::System.Web.UI.WebControls.Literal litLblSelector;
        protected global::System.Web.UI.WebControls.Literal litHintSelector;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.Literal litLblTitle;
        protected global::System.Web.UI.WebControls.TextBox txtTitleEn;
        protected global::System.Web.UI.WebControls.Literal litLblTitleEn;

        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.Literal litLblDesc;
        protected global::System.Web.UI.WebControls.TextBox txtDescEn;
        protected global::System.Web.UI.WebControls.Literal litLblDescEn;

        protected global::System.Web.UI.WebControls.TextBox txtBadge;
        protected global::System.Web.UI.WebControls.Literal litLblBadge;
        protected global::System.Web.UI.WebControls.TextBox txtBadgeEn;
        protected global::System.Web.UI.WebControls.Literal litLblBadgeEn;
        protected global::System.Web.UI.WebControls.TextBox txtMeta;
        protected global::System.Web.UI.WebControls.Literal litLblMeta;
        protected global::System.Web.UI.WebControls.TextBox txtMetaEn;
        protected global::System.Web.UI.WebControls.Literal litLblMetaEn;

        protected global::System.Web.UI.WebControls.TextBox txtLinkUrl;
        protected global::System.Web.UI.WebControls.Literal litLblLink;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Literal litLblActive;

        protected global::System.Web.UI.WebControls.LinkButton btnSave;
        protected global::System.Web.UI.WebControls.Literal litSave;
        protected global::System.Web.UI.WebControls.LinkButton btnCancel;
        protected global::System.Web.UI.WebControls.Literal litCancel;

        protected global::System.Web.UI.WebControls.Literal litColOrder;
        protected global::System.Web.UI.WebControls.Literal litColTitle;
        protected global::System.Web.UI.WebControls.Literal litColBadge;
        protected global::System.Web.UI.WebControls.Literal litColActive;
        protected global::System.Web.UI.WebControls.Literal litColActions;

        protected global::System.Web.UI.WebControls.Repeater rptUnits;
    }
}
