//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.About.OrgStructure
{
    public partial class ucOrgStructure
    {
        /// <summary>
        /// litUnitsJson control. Emits the injected unit JSON + config script block.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUnitsJson;
    }
}
