//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Shared.About
{
    public partial class ucAgencyDeputyWelcomeDga
    {
        protected global::System.Web.UI.WebControls.Literal litDeputyHeading;
        protected global::System.Web.UI.WebControls.Literal litDeputyBody;
        protected global::System.Web.UI.WebControls.Literal litDeputyRoleTitle;
        protected global::System.Web.UI.WebControls.Literal litDeputyRoleSubtitle;
    }
}
