//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Shared.About
{
    public partial class ucAgencyOverviewDga
    {
        protected global::System.Web.UI.WebControls.Literal litOverviewHeading;
        protected global::System.Web.UI.WebControls.Literal litOverviewIntro;
        protected global::System.Web.UI.WebControls.Literal litVisionTitle;
        protected global::System.Web.UI.WebControls.Literal litVisionBody;
        protected global::System.Web.UI.WebControls.Literal litMissionTitle;
        protected global::System.Web.UI.WebControls.Literal litMissionBody;
        protected global::System.Web.UI.WebControls.Literal litObjectivesTitle;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgOverview;
        protected global::System.Web.UI.WebControls.Repeater rptObjectives;
    }
}
