//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Shared.About
{


    public partial class ucSharedDocuments
    {

        /// <summary>
        /// secDocuments control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl secDocuments;

        /// <summary>
        /// litHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litHeading;

        /// <summary>
        /// rptCategories control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCategories;
    }
}
