//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA
{


    public partial class ucAgencyDetails
    {

        /// <summary>
        /// ucOverview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA.ucAgOverview ucOverview;

        /// <summary>
        /// ucCards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA.ucAgCards ucCards;

        /// <summary>
        /// ucObjectives control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA.ucAgObjectives ucObjectives;

        /// <summary>
        /// ucDeputyWord control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA.ucAgDeputyWord ucDeputyWord;

        /// <summary>
        /// ucMainTasks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Agency.DGA.ucAgMainTasks ucMainTasks;

    }
}
