//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Tawasul.Controls
{


    public partial class ucTwLocation
    {

        /// <summary>ltSectionTitle control.</summary>
        protected global::System.Web.UI.WebControls.Literal ltSectionTitle;

        /// <summary>ltAddress control.</summary>
        protected global::System.Web.UI.WebControls.Literal ltAddress;

        /// <summary>phMap control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMap;

        /// <summary>ltMap control.</summary>
        protected global::System.Web.UI.WebControls.Literal ltMap;

        /// <summary>secLocation control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl secLocation;
    }
}
