//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإضافة بنجاح..
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار ملف واحد على الأقل لتعديله..
        /// </summary>
        internal static string AtLeastOneDocShouldSelected {
            get {
                return ResourceManager.GetString("AtLeastOneDocShouldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإمتدادت المسموح بها فقط هيا: {0}.
        /// </summary>
        internal static string AttachmentsAllowedExtensionErrorMessage {
            get {
                return ResourceManager.GetString("AttachmentsAllowedExtensionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تخطى الملف الحجم المسموح به و هو {0} ميجابيت.
        /// </summary>
        internal static string AttachmentsMaxSizeErrorMessage {
            get {
                return ResourceManager.GetString("AttachmentsMaxSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك حذف العنصر لارتباطه بعناصر أخرى .
        /// </summary>
        internal static string CantDeleteError {
            get {
                return ResourceManager.GetString("CantDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        internal static string CompleteSuccessfully {
            get {
                return ResourceManager.GetString("CompleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح..
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في بيانات الصفحة..
        /// </summary>
        internal static string InvalidParametersError {
            get {
                return ResourceManager.GetString("InvalidParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ خلال إضافة العنصر..
        /// </summary>
        internal static string ItemAddingError {
            get {
                return ResourceManager.GetString("ItemAddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ خلال حذف العنصر..
        /// </summary>
        internal static string ItemDeletingError {
            get {
                return ResourceManager.GetString("ItemDeletingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر المطلوب غير موجود بالنظام..
        /// </summary>
        internal static string ItemNotFoundError {
            get {
                return ResourceManager.GetString("ItemNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ خلال تعديل العنصر..
        /// </summary>
        internal static string ItemUpdatingError {
            get {
                return ResourceManager.GetString("ItemUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يحتوي على رقم بين {0} و {1}.
        /// </summary>
        internal static string NumberRangeValidationErrorMessage {
            get {
                return ResourceManager.GetString("NumberRangeValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة مرفقات للطلب.
        /// </summary>
        internal static string RequiredAttachmentError {
            get {
                return ResourceManager.GetString("RequiredAttachmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال قيمة لـ {0}.
        /// </summary>
        internal static string RequiredFieldErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFieldErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنت لا تملك الصلاحيات الكافية لهذة الصفحة..
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع، يرجى مراجعة مسؤول النظام..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح..
        /// </summary>
        internal static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
