//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.AppGlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PNUres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PNUres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PNU.Internet.WebParts.AppGlobalResources.PNUres", typeof(PNUres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن المركز.
        /// </summary>
        internal static string AboutCenter {
            get {
                return ResourceManager.GetString("AboutCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرة عامة.
        /// </summary>
        internal static string AboutFaculty {
            get {
                return ResourceManager.GetString("AboutFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن البرنامج الأكاديمي .
        /// </summary>
        internal static string AboutProgram {
            get {
                return ResourceManager.GetString("AboutProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن القسم .
        /// </summary>
        internal static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماداتنا الأكاديمية.
        /// </summary>
        internal static string AcademicCredits {
            get {
                return ResourceManager.GetString("AcademicCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة العلمية التي يمنحها البرنامج ..
        /// </summary>
        internal static string AcademicDegree {
            get {
                return ResourceManager.GetString("AcademicDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرامج الأكاديمية للقسم.
        /// </summary>
        internal static string AcademicPrograms {
            get {
                return ResourceManager.GetString("AcademicPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرامج الأكاديمية للكلية.
        /// </summary>
        internal static string AcademicProgramsCollege {
            get {
                return ResourceManager.GetString("AcademicProgramsCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهام الوكالة.
        /// </summary>
        internal static string AgencyMissions {
            get {
                return ResourceManager.GetString("AgencyMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم.
        /// </summary>
        internal static string AICalender {
            get {
                return ResourceManager.GetString("AICalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        internal static string AIContactUS {
            get {
                return ResourceManager.GetString("AIContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء المركز.
        /// </summary>
        internal static string AIMembers {
            get {
                return ResourceManager.GetString("AIMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبار المركز.
        /// </summary>
        internal static string AIRecentNews {
            get {
                return ResourceManager.GetString("AIRecentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جميع الإعلانات.
        /// </summary>
        internal static string AllAdvsLink {
            get {
                return ResourceManager.GetString("AllAdvsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكليات والمعاهد.
        /// </summary>
        internal static string AllFacultiesAndInstitues {
            get {
                return ResourceManager.GetString("AllFacultiesAndInstitues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الأنظمة.
        /// </summary>
        internal static string AllSystems {
            get {
                return ResourceManager.GetString("AllSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائيات الخريجات.
        /// </summary>
        internal static string Alumni_dashboard {
            get {
                return ResourceManager.GetString("Alumni-dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخريجات في سوق العمل.
        /// </summary>
        internal static string Alumni_dashboard_G {
            get {
                return ResourceManager.GetString("Alumni-dashboard-G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعلانات.
        /// </summary>
        internal static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإعلانات :.
        /// </summary>
        internal static string AnnouncementsNo {
            get {
                return ResourceManager.GetString("AnnouncementsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير السنوية.
        /// </summary>
        internal static string AnnualReports {
            get {
                return ResourceManager.GetString("AnnualReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأساتذة المساعدون.
        /// </summary>
        internal static string AssistantProfessors {
            get {
                return ResourceManager.GetString("AssistantProfessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأساتذة المشاركون.
        /// </summary>
        internal static string AssociateProfessors {
            get {
                return ResourceManager.GetString("AssociateProfessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المبنى: 170.
        /// </summary>
        internal static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجالات العمل.
        /// </summary>
        internal static string CareerOpportunities {
            get {
                return ResourceManager.GetString("CareerOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع المركز:.
        /// </summary>
        internal static string CentreLocation {
            get {
                return ResourceManager.GetString("CentreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قنوات تقديم الخدمة.
        /// </summary>
        internal static string Channels {
            get {
                return ResourceManager.GetString("Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف:.
        /// </summary>
        internal static string Classification {
            get {
                return ResourceManager.GetString("Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح الكل.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Style%20Library/NewStyle/UI5/images/coiled-arrow.png.
        /// </summary>
        internal static string coiledarrow {
            get {
                return ResourceManager.GetString("coiledarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلية.
        /// </summary>
        internal static string COLLEGE {
            get {
                return ResourceManager.GetString("COLLEGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات الإدارية التابعة للكلية.
        /// </summary>
        internal static string CollegeDepartments {
            get {
                return ResourceManager.GetString("CollegeDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظرة عامة عن .
        /// </summary>
        internal static string CollegeOverviewPrefix {
            get {
                return ResourceManager.GetString("CollegeOverviewPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات الكلية الاختيارية.
        /// </summary>
        internal static string CollegeRequisites {
            get {
                return ResourceManager.GetString("CollegeRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكليات.
        /// </summary>
        internal static string Colleges {
            get {
                return ResourceManager.GetString("Colleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التواصل.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد أبحاث جوجل :.
        /// </summary>
        internal static string CountGoogle {
            get {
                return ResourceManager.GetString("CountGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقالات أوركيد.
        /// </summary>
        internal static string CountORCID {
            get {
                return ResourceManager.GetString("CountORCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المقرر.
        /// </summary>
        internal static string COURSE_TITLE {
            get {
                return ResourceManager.GetString("COURSE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المقرر.
        /// </summary>
        internal static string CourseCode {
            get {
                return ResourceManager.GetString("CourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد الدراسية.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشعبة.
        /// </summary>
        internal static string CourseSEQ {
            get {
                return ResourceManager.GetString("CourseSEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول المقررات.
        /// </summary>
        internal static string CoursesTable {
            get {
                return ResourceManager.GetString("CoursesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواعيد المقرر.
        /// </summary>
        internal static string CoursesTime {
            get {
                return ResourceManager.GetString("CoursesTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المقرر.
        /// </summary>
        internal static string CourseTitle {
            get {
                return ResourceManager.GetString("CourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الوحدات المطلوبة.
        /// </summary>
        internal static string CREDIT {
            get {
                return ResourceManager.GetString("CREDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلية علوم الحاسب والمعلومات.
        /// </summary>
        internal static string CSCollege {
            get {
                return ResourceManager.GetString("CSCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيرة الذاتية.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        internal static string DayName {
            get {
                return ResourceManager.GetString("DayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارات التابعة للعمادة.
        /// </summary>
        internal static string DeanshipDepartments {
            get {
                return ResourceManager.GetString("DeanshipDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهام &lt;br&gt; العمادة.
        /// </summary>
        internal static string DeanshipMission {
            get {
                return ResourceManager.GetString("DeanshipMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة عميد/ة الكلية.
        /// </summary>
        internal static string DeenSpeech {
            get {
                return ResourceManager.GetString("DeenSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهام &lt;br&gt; الإدارة.
        /// </summary>
        internal static string DepartmentMission {
            get {
                return ResourceManager.GetString("DepartmentMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستندات / البيانات المطلوبة.
        /// </summary>
        internal static string DocumentAndData {
            get {
                return ResourceManager.GetString("DocumentAndData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة المستهدفة.
        /// </summary>
        internal static string DP_TargetGroup {
            get {
                return ResourceManager.GetString("DP_TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني :.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائيات الموظفين.
        /// </summary>
        internal static string employee_dashboard {
            get {
                return ResourceManager.GetString("employee-dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى الساعة.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنظمة و الخدمات الإلكترونية.
        /// </summary>
        internal static string EServices {
            get {
                return ResourceManager.GetString("EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/Pages/Eservice.aspx.
        /// </summary>
        internal static string EServicesURL {
            get {
                return ResourceManager.GetString("EServicesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت تنفيذ الخدمة.
        /// </summary>
        internal static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التحويلة :.
        /// </summary>
        internal static string ExtensionNo {
            get {
                return ResourceManager.GetString("ExtensionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء هيئة التدريس.
        /// </summary>
        internal static string FacultyMembers {
            get {
                return ResourceManager.GetString("FacultyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء هيئة التدريس.
        /// </summary>
        internal static string FacultyMemberSearch {
            get {
                return ResourceManager.GetString("FacultyMemberSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلية.
        /// </summary>
        internal static string FacultyTitle {
            get {
                return ResourceManager.GetString("FacultyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الخامسة.
        /// </summary>
        internal static string FifthYear {
            get {
                return ResourceManager.GetString("FifthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الأولي.
        /// </summary>
        internal static string FirstYear {
            get {
                return ResourceManager.GetString("FirstYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور: الثاني.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الرابعة.
        /// </summary>
        internal static string FourthYear {
            get {
                return ResourceManager.GetString("FourthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلفات والإهتمامات البحثية.
        /// </summary>
        internal static string GoogleScholar {
            get {
                return ResourceManager.GetString("GoogleScholar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير قياس نسب توظيف الخريجات.
        /// </summary>
        internal static string GraduationEmployements {
            get {
                return ResourceManager.GetString("GraduationEmployements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوابة الخريجات.
        /// </summary>
        internal static string GradutesLink {
            get {
                return ResourceManager.GetString("GradutesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط لتحميل دليل الاستخدام.
        /// </summary>
        internal static string guide {
            get {
                return ResourceManager.GetString("guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل دليل الاستخدام.
        /// </summary>
        internal static string guideDownload {
            get {
                return ResourceManager.GetString("guideDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدلة الإرشادية.
        /// </summary>
        internal static string GuidelinesTitle {
            get {
                return ResourceManager.GetString("GuidelinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دليل الاستخدام.
        /// </summary>
        internal static string guideManual {
            get {
                return ResourceManager.GetString("guideManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهم الأنظمة.
        /// </summary>
        internal static string ImportantSystems {
            get {
                return ResourceManager.GetString("ImportantSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جولة تعريفية.
        /// </summary>
        internal static string IntroductoryTour {
            get {
                return ResourceManager.GetString("IntroductoryTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تقييم هذه الخدمة بمتوسط.
        /// </summary>
        internal static string L_RatedAverage {
            get {
                return ResourceManager.GetString("L_RatedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم هذه الخدمة.
        /// </summary>
        internal static string L_RateThis {
            get {
                return ResourceManager.GetString("L_RateThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقييم.
        /// </summary>
        internal static string L_Rating {
            get {
                return ResourceManager.GetString("L_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ar/.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر الإعلانات.
        /// </summary>
        internal static string LatestAdvs {
            get {
                return ResourceManager.GetString("LatestAdvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحدث الفعاليات.
        /// </summary>
        internal static string LatestEvents {
            get {
                return ResourceManager.GetString("LatestEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر الأخبار.
        /// </summary>
        internal static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string lblEmailAddress {
            get {
                return ResourceManager.GetString("lblEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        internal static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير.
        /// </summary>
        internal static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالتك.
        /// </summary>
        internal static string lblMessege {
            get {
                return ResourceManager.GetString("lblMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاضرون.
        /// </summary>
        internal static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الأول.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الثاني.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الثالث.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الرابع.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الخامس.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى السادس.
        /// </summary>
        internal static string Level6 {
            get {
                return ResourceManager.GetString("Level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى السابع.
        /// </summary>
        internal static string Level7 {
            get {
                return ResourceManager.GetString("Level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الثامن.
        /// </summary>
        internal static string Level8 {
            get {
                return ResourceManager.GetString("Level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى التاسع.
        /// </summary>
        internal static string Level9 {
            get {
                return ResourceManager.GetString("Level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستويات.
        /// </summary>
        internal static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الساعات المكتبية.
        /// </summary>
        internal static string LibraryHours {
            get {
                return ResourceManager.GetString("LibraryHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Style Library/NewStyle/UI5/images/pnu-logo-ar.svg.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهام الرئيسية.
        /// </summary>
        internal static string MainMissions {
            get {
                return ResourceManager.GetString("MainMissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص.
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المركز الإعلامي.
        /// </summary>
        internal static string MediaCenter {
            get {
                return ResourceManager.GetString("MediaCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص الدقيق.
        /// </summary>
        internal static string minor {
            get {
                return ResourceManager.GetString("minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النشرات الدورية.
        /// </summary>
        internal static string NewsArticles {
            get {
                return ResourceManager.GetString("NewsArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد متطلبات لهذا البرنامج.
        /// </summary>
        internal static string NoProgramRequirements {
            get {
                return ResourceManager.GetString("NoProgramRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم / الإدارة.
        /// </summary>
        internal static string NoraNabtakertxtDepartment {
            get {
                return ResourceManager.GetString("NoraNabtakertxtDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة العمل / الكلية.
        /// </summary>
        internal static string NoraNabtakertxtWork {
            get {
                return ResourceManager.GetString("NoraNabtakertxtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب بيانات مفتوحة.
        /// </summary>
        internal static string OpenDataTitle {
            get {
                return ResourceManager.GetString("OpenDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض النشرة.
        /// </summary>
        internal static string openTitle {
            get {
                return ResourceManager.GetString("openTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأوركيد.
        /// </summary>
        internal static string ORCID {
            get {
                return ResourceManager.GetString("ORCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحبتنا.
        /// </summary>
        internal static string OurLoveredOnes {
            get {
                return ResourceManager.GetString("OurLoveredOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقسامنا.
        /// </summary>
        internal static string OurSections {
            get {
                return ResourceManager.GetString("OurSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيم.
        /// </summary>
        internal static string OurValues {
            get {
                return ResourceManager.GetString("OurValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براءات الاختراع.
        /// </summary>
        internal static string patents_dashboard {
            get {
                return ResourceManager.GetString("patents-dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات البرنامج الاختيارية.
        /// </summary>
        internal static string PLANS_ELEC_P_Requirements {
            get {
                return ResourceManager.GetString("PLANS_ELEC_P_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعاليات PNU.
        /// </summary>
        internal static string pnu_events {
            get {
                return ResourceManager.GetString("pnu_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعة الأميرة نورة.
        /// </summary>
        internal static string PNU_KSA {
            get {
                return ResourceManager.GetString("PNU_KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباشر PNU.
        /// </summary>
        internal static string pnu_live {
            get {
                return ResourceManager.GetString("pnu_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصميم وتطوير الإدارة العامة للتحول الرقمي.
        /// </summary>
        internal static string PNU_TradeDepart {
            get {
                return ResourceManager.GetString("PNU_TradeDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخر تحديث للبوابة في 05 مايو 2024.
        /// </summary>
        internal static string PNU_TradeLastModified {
            get {
                return ResourceManager.GetString("PNU_TradeLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامعة الأميرة نورة بنت عبدالرحمن © 2024.
        /// </summary>
        internal static string PNU_TradeMark {
            get {
                return ResourceManager.GetString("PNU_TradeMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجامعة في أرقام.
        /// </summary>
        internal static string PNUinNumbers {
            get {
                return ResourceManager.GetString("PNUinNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتطلب السابق.
        /// </summary>
        internal static string PreRequisite {
            get {
                return ResourceManager.GetString("PreRequisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوائز.
        /// </summary>
        internal static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأساتذة.
        /// </summary>
        internal static string Professors {
            get {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد السنوات.
        /// </summary>
        internal static string ProgDuration {
            get {
                return ResourceManager.GetString("ProgDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغة التدريس.
        /// </summary>
        internal static string ProgLanguage {
            get {
                return ResourceManager.GetString("ProgLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الدراسة.
        /// </summary>
        internal static string ProgramDetails {
            get {
                return ResourceManager.GetString("ProgramDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطبيعة الأكاديمية للتخصص.
        /// </summary>
        internal static string ProgramNature {
            get {
                return ResourceManager.GetString("ProgramNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات البرنامج الاختيارية.
        /// </summary>
        internal static string ProgramRequisites {
            get {
                return ResourceManager.GetString("ProgramRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراءة المزيد.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجراءات الأكاديمية.
        /// </summary>
        internal static string RegDepartments {
            get {
                return ResourceManager.GetString("RegDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جميع  الفعاليات.
        /// </summary>
        internal static string res_AllEvents {
            get {
                return ResourceManager.GetString("res_AllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الكل.
        /// </summary>
        internal static string res_AllNews {
            get {
                return ResourceManager.GetString("res_AllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string res_Cancel {
            get {
                return ResourceManager.GetString("res_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق.
        /// </summary>
        internal static string res_Comment {
            get {
                return ResourceManager.GetString("res_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل دليل المستخدم.
        /// </summary>
        internal static string res_DownloadUserGuide {
            get {
                return ResourceManager.GetString("res_DownloadUserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string res_Email {
            get {
                return ResourceManager.GetString("res_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات الإلكترونية.
        /// </summary>
        internal static string res_EServices {
            get {
                return ResourceManager.GetString("res_EServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسئلة الشائعة.
        /// </summary>
        internal static string res_FAQ {
            get {
                return ResourceManager.GetString("res_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة الأسئلة الشائعة.
        /// </summary>
        internal static string res_FAQPage {
            get {
                return ResourceManager.GetString("res_FAQPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        internal static string res_Female {
            get {
                return ResourceManager.GetString("res_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الملف.
        /// </summary>
        internal static string res_FileName {
            get {
                return ResourceManager.GetString("res_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string res_Home {
            get {
                return ResourceManager.GetString("res_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ آخر تعديل: &lt;time datetime=&quot;{0}&quot;&gt;{1} بتوقيت السعودية&lt;/time&gt;.
        /// </summary>
        internal static string res_LastModified {
            get {
                return ResourceManager.GetString("res_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحدث الأخبار.
        /// </summary>
        internal static string res_LatestNews {
            get {
                return ResourceManager.GetString("res_LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string res_Male {
            get {
                return ResourceManager.GetString("res_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الإعلانات.
        /// </summary>
        internal static string res_MoreAllAdvsLink {
            get {
                return ResourceManager.GetString("res_MoreAllAdvsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من الأخبار.
        /// </summary>
        internal static string res_MoreAllNews {
            get {
                return ResourceManager.GetString("res_MoreAllNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار والإعلانات.
        /// </summary>
        internal static string res_NewsAndEvents {
            get {
                return ResourceManager.GetString("res_NewsAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string res_No {
            get {
                return ResourceManager.GetString("res_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        internal static string res_NotAvailable {
            get {
                return ResourceManager.GetString("res_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل عدم القول.
        /// </summary>
        internal static string res_PreferNotToSay {
            get {
                return ResourceManager.GetString("res_PreferNotToSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تقييم هذه الخدمة بمتوسط &lt;span class=&quot;fw-semibold&quot;&gt;{0}&lt;/span&gt;.
        /// </summary>
        internal static string res_RatedAverage {
            get {
                return ResourceManager.GetString("res_RatedAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم هذه الخدمة.
        /// </summary>
        internal static string res_RateThisService {
            get {
                return ResourceManager.GetString("res_RateThisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم بـ {0} نجمه.
        /// </summary>
        internal static string res_RateWithStars {
            get {
                return ResourceManager.GetString("res_RateWithStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبرنا عن تجربتك في هذه الخدمة.
        /// </summary>
        internal static string res_RatingCommentLabel {
            get {
                return ResourceManager.GetString("res_RatingCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيف تقيم هذه الخدمة؟.
        /// </summary>
        internal static string res_RatingHowRate {
            get {
                return ResourceManager.GetString("res_RatingHowRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى عدم تضمين معلومات شخصية أو مالية. سيتم إرسال تعليقك وتسجيله لغرض تحسين الخدمات..
        /// </summary>
        internal static string res_RatingPrivacyNote {
            get {
                return ResourceManager.GetString("res_RatingPrivacyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيم تجربتك من (1) ضعيف إلى (5) ممتاز.
        /// </summary>
        internal static string res_RatingScale {
            get {
                return ResourceManager.GetString("res_RatingScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تقييم.
        /// </summary>
        internal static string res_RatingsCount {
            get {
                return ResourceManager.GetString("res_RatingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبرنا عن رأيك في هذه الخدمة.
        /// </summary>
        internal static string res_RatingTellUs {
            get {
                return ResourceManager.GetString("res_RatingTellUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرًا لك، تم تسجيل تقييمك بنجاح..
        /// </summary>
        internal static string res_RatingThankYou {
            get {
                return ResourceManager.GetString("res_RatingThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستندات المطلوبة.
        /// </summary>
        internal static string res_RequiredDocuments {
            get {
                return ResourceManager.GetString("res_RequiredDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قنوات الخدمة.
        /// </summary>
        internal static string res_ServiceChannels {
            get {
                return ResourceManager.GetString("res_ServiceChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكلفة الخدمة.
        /// </summary>
        internal static string res_ServiceCost {
            get {
                return ResourceManager.GetString("res_ServiceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الخدمة.
        /// </summary>
        internal static string res_ServiceDuration {
            get {
                return ResourceManager.GetString("res_ServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمة متاحة باللغة.
        /// </summary>
        internal static string res_ServiceLanguage {
            get {
                return ResourceManager.GetString("res_ServiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات الخدمة.
        /// </summary>
        internal static string res_ServiceRequirements {
            get {
                return ResourceManager.GetString("res_ServiceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاركة الصفحة.
        /// </summary>
        internal static string res_SharePage {
            get {
                return ResourceManager.GetString("res_SharePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المزيد.
        /// </summary>
        internal static string res_ShowMore {
            get {
                return ResourceManager.GetString("res_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتفاقية مستوى الخدمة.
        /// </summary>
        internal static string res_SLA {
            get {
                return ResourceManager.GetString("res_SLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدء الخدمة.
        /// </summary>
        internal static string res_StartService {
            get {
                return ResourceManager.GetString("res_StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطوات.
        /// </summary>
        internal static string res_Steps {
            get {
                return ResourceManager.GetString("res_Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string res_Submit {
            get {
                return ResourceManager.GetString("res_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انا.
        /// </summary>
        internal static string res_SurveyIAm {
            get {
                return ResourceManager.GetString("res_SurveyIAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكنك تحديد خيارات متعددة.
        /// </summary>
        internal static string res_SurveyMultiSelect {
            get {
                return ResourceManager.GetString("res_SurveyMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جعل التخطيط من السهل القراءة.
        /// </summary>
        internal static string res_SurveyReasonLayout {
            get {
                return ResourceManager.GetString("res_SurveyReasonLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيء آخر.
        /// </summary>
        internal static string res_SurveyReasonOther {
            get {
                return ResourceManager.GetString("res_SurveyReasonOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى ذو صلة.
        /// </summary>
        internal static string res_SurveyReasonRelevant {
            get {
                return ResourceManager.GetString("res_SurveyReasonRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد كانت مكتوبة بشكل جيد.
        /// </summary>
        internal static string res_SurveyReasonWellWritten {
            get {
                return ResourceManager.GetString("res_SurveyReasonWellWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;fw-semibold&quot;&gt;{0}%&lt;/span&gt; من المستخدمين قالوا نعم من &lt;span class=&quot;fw-semibold&quot;&gt;{1}&lt;/span&gt; تعليقًا.
        /// </summary>
        internal static string res_SurveyStats {
            get {
                return ResourceManager.GetString("res_SurveyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أخبرنا بالسبب.
        /// </summary>
        internal static string res_SurveyTellUsWhy {
            get {
                return ResourceManager.GetString("res_SurveyTellUsWhy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرًا لك، تم إرسال ملاحظاتك بنجاح..
        /// </summary>
        internal static string res_SurveyThankYou {
            get {
                return ResourceManager.GetString("res_SurveyThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل كانت هذه الصفحة مفيدة؟.
        /// </summary>
        internal static string res_SurveyWasHelpful {
            get {
                return ResourceManager.GetString("res_SurveyWasHelpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة المستهدفة.
        /// </summary>
        internal static string res_TargetAudience {
            get {
                return ResourceManager.GetString("res_TargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        internal static string res_Telephone {
            get {
                return ResourceManager.GetString("res_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string res_Yes {
            get {
                return ResourceManager.GetString("res_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائيات الأبحاث.
        /// </summary>
        internal static string Research_paper {
            get {
                return ResourceManager.GetString("Research-paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسارات البحثية.
        /// </summary>
        internal static string ResearchPaths {
            get {
                return ResourceManager.GetString("ResearchPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة المسؤولة.
        /// </summary>
        internal static string ResponsibleParty {
            get {
                return ResourceManager.GetString("ResponsibleParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرتبة العلمية.
        /// </summary>
        internal static string ScientifDegree {
            get {
                return ResourceManager.GetString("ScientifDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزه.
        /// </summary>
        internal static string SCRATTR_SUBJ_CODE {
            get {
                return ResourceManager.GetString("SCRATTR_SUBJ_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث بالاسم.
        /// </summary>
        internal static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الثانية.
        /// </summary>
        internal static string SecondYear {
            get {
                return ResourceManager.GetString("SecondYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        internal static string section {
            get {
                return ResourceManager.GetString("section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسم .
        /// </summary>
        internal static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --اختر--.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- اختر الكلية --.
        /// </summary>
        internal static string SelectCollege {
            get {
                return ResourceManager.GetString("SelectCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- اختر القسم --.
        /// </summary>
        internal static string SelectSection {
            get {
                return ResourceManager.GetString("SelectSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتفاقية مستوى الخدمة.
        /// </summary>
        internal static string ServiceQuality {
            get {
                return ResourceManager.GetString("ServiceQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة السابعة.
        /// </summary>
        internal static string SeventhYear {
            get {
                return ResourceManager.GetString("SeventhYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاركة الصفحة.
        /// </summary>
        internal static string SharePage {
            get {
                return ResourceManager.GetString("SharePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة السادسة.
        /// </summary>
        internal static string SixthYear {
            get {
                return ResourceManager.GetString("SixthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التخصص العام.
        /// </summary>
        internal static string specialization {
            get {
                return ResourceManager.GetString("specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشؤون الرياضية.
        /// </summary>
        internal static string Sports {
            get {
                return ResourceManager.GetString("Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبدأ الخدمة.
        /// </summary>
        internal static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من الساعة.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأهداف الاستراتيجية لجامعة الأميرة نورة.
        /// </summary>
        internal static string StrategicPlan {
            get {
                return ResourceManager.GetString("StrategicPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحصائيات الطالبات.
        /// </summary>
        internal static string students_dashboard {
            get {
                return ResourceManager.GetString("students-dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطة الدراسية والمقررات.
        /// </summary>
        internal static string StudyPlan {
            get {
                return ResourceManager.GetString("StudyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشعبة.
        /// </summary>
        internal static string SubjectSectionNo {
            get {
                return ResourceManager.GetString("SubjectSectionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استبيان.
        /// </summary>
        internal static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعيدون.
        /// </summary>
        internal static string TeachingAssistants {
            get {
                return ResourceManager.GetString("TeachingAssistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشروط والاحكام.
        /// </summary>
        internal static string terms_and_conditions {
            get {
                return ResourceManager.GetString("terms-and-conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط لتحميل الشروط والاحكام.
        /// </summary>
        internal static string terms_and_conditions_click {
            get {
                return ResourceManager.GetString("terms-and-conditions-click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الثالثة.
        /// </summary>
        internal static string ThirdYear {
            get {
                return ResourceManager.GetString("ThirdYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم محطة القطار: A 3.
        /// </summary>
        internal static string TrainStationNumber {
            get {
                return ResourceManager.GetString("TrainStationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التدوينات.
        /// </summary>
        internal static string Tweets {
            get {
                return ResourceManager.GetString("Tweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التدوينات :.
        /// </summary>
        internal static string TweetsNo {
            get {
                return ResourceManager.GetString("TweetsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب بيانات مفتوحة إضافية.
        /// </summary>
        internal static string txtOpenDataRequest {
            get {
                return ResourceManager.GetString("txtOpenDataRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقترحات.
        /// </summary>
        internal static string txtSuggest {
            get {
                return ResourceManager.GetString("txtSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقويم الجامعي.
        /// </summary>
        internal static string UniversityCalender {
            get {
                return ResourceManager.GetString("UniversityCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجلس الجامعة.
        /// </summary>
        internal static string UniversityCounsil {
            get {
                return ResourceManager.GetString("UniversityCounsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الجامعة.
        /// </summary>
        internal static string UniversityHistory {
            get {
                return ResourceManager.GetString("UniversityHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متطلبات الجامعة.
        /// </summary>
        internal static string UniversityRequisites {
            get {
                return ResourceManager.GetString("UniversityRequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنوات.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
