//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file may cause unexpected behavior.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Admin
{
    public partial class DynamicMenuLoader
    {
        protected global::System.Web.UI.WebControls.Literal litErrors;
        protected global::System.Web.UI.WebControls.Repeater rptMenu;
        protected global::System.Web.UI.WebControls.PlaceHolder phContent;
        protected global::System.Web.UI.WebControls.Literal litEmpty;
    }
}
