//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.ITAdmin
{
    public partial class ucPageCreator
    {
        protected global::System.Web.UI.WebControls.Panel pnlDenied;
        protected global::System.Web.UI.WebControls.Literal litDeniedMsg;
        protected global::System.Web.UI.WebControls.Panel pnlForm;
        protected global::System.Web.UI.WebControls.Literal litPageHeader;
        protected global::System.Web.UI.WebControls.Panel pnlValidation;
        protected global::System.Web.UI.WebControls.Literal litValidationMsg;
        protected global::System.Web.UI.WebControls.Label lblWebSiteUrl;
        protected global::System.Web.UI.WebControls.TextBox txtWebSiteUrl;
        protected global::System.Web.UI.WebControls.Literal litWebSiteUrlHint;
        protected global::System.Web.UI.WebControls.Label lblTemplate;
        protected global::System.Web.UI.WebControls.DropDownList ddlTemplate;
        protected global::System.Web.UI.WebControls.Literal litTemplateHint;
        protected global::System.Web.UI.WebControls.Label lblPageLayout;
        protected global::System.Web.UI.WebControls.DropDownList ddlPageLayout;
        protected global::System.Web.UI.WebControls.Literal litLayoutHint;
        protected global::System.Web.UI.WebControls.Label lblPageName;
        protected global::System.Web.UI.WebControls.TextBox txtPageName;
        protected global::System.Web.UI.WebControls.Label lblTitleAr;
        protected global::System.Web.UI.WebControls.TextBox txtPageTitleAr;
        protected global::System.Web.UI.WebControls.Label lblTitleEn;
        protected global::System.Web.UI.WebControls.TextBox txtPageTitleEn;
        protected global::System.Web.UI.WebControls.Label lblUcProperties;
        protected global::System.Web.UI.WebControls.TextBox txtUcProperties;
        protected global::System.Web.UI.WebControls.Literal litUcPropertiesHint;
        protected global::System.Web.UI.WebControls.CheckBox chkBothSites;
        protected global::System.Web.UI.WebControls.Label lblBothSites;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.HiddenField hfUcPath;
        protected global::System.Web.UI.WebControls.Panel pnlResults;
        protected global::System.Web.UI.WebControls.Literal litResultsHeader;
        protected global::System.Web.UI.WebControls.Repeater rptResults;
    }
}
