//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes may be overwritten. Named controls inside the Repeater
//     ItemTemplate are NOT declared here — resolve them with FindControl in
//     ItemDataBound if ever needed.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNU.Internet.WebParts.CONTROLTEMPLATES.PNU.Internet.Policies
{
    public partial class ucNavCards
    {
        /// <summary>rptCards control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptCards;
    }
}
